baseURL = "https://jtamagnan.com"
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Jules Tamagnan"
[author]
  gravatarEmail = "jtamagnan@gmail.com"
  homepageText = "Jules Tamagnan"
  name = "Jules Tamagnan"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
[params]
  description = "A bit about me."
  licence = false
  displayPostLanguage = false
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[markup.goldmark.renderer]
unsafe= true