baseURL = "https://jtamagnan.com"
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsStyle = "monokai"
pygmentsuseclasses = false
theme = "simplicity"
title = "Jules Tamagnan"
publishDir = "./.build/public"
resourceDir = "./.build/resources"
[params.author]
  gravatarEmail = "jtamagnan@gmail.com"
  name = "Jules Tamagnan"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
[params]
  description = "A bit about me."
  licence = false
  displayPostLanguage = false
[permalinks]
  posts = "/posts/:slug/"
  recipes = "/recipes/:slug/"
[pygmentsOptions]
  linenos = false
[markup.goldmark.renderer]
unsafe= true