[build]
publish = "./.build/public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/resume/*"
to = "/Tamagnan_Jules_resume.pdf"
status = 301
force = true

[[redirects]]
from = "/github/*"
to = "https://github.com/jtamagnan"
status = 301

[[redirects]]
from = "/linkedin/*"
to = "https://linkedin.com/in/jtamagnan"
status = 301
